name: Build Project and Deploy via SSH

on:
  push:
    branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
          matrix:
            node-version: [17.x]
        
        steps:
         -  name: Checkout
            uses: actions/checkout@v2
        
         -  name: Setup Node
            uses: actions/setup-node@v2
            with: 
                node-verison: ${{matrix.node-version}}
            
         -  name: Install Deps
            run: npm ci

         -  name: Build Project
            run: npm run build

         -  name: Upload via SCP
            uses: appleboy/scp-action@v0.1.7
            with:
                source: dist/
                target: /var/www/html
                host: ${{secrets.SSH_HOST}}
                username: ${{secrets.SSH_USERNAME}}
                password: ${{secrets.SSH_PASSWORD}}
                port: 22
